baseURL: "https://nikiforovanina.github.io/"
title: Nina Nikiforova
theme: PaperMod
pagination:
  pagerSize: 20
enableInlineShortcodes: true
enableRobotsTXT: true

params:
  description: "PhD Student in Economics at Bocconi University"
  author: Nina Nikiforova
  defaultTheme: light
  disableThemeToggle: true
  hideFooter: true
  ShowReadingTime: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableScrollToTop: true
  disableSpecial1stPost: true
  ShowToc: false
  
  # Enable custom profile mode
  profileMode:
    enabled: true
    title: ""  # We'll handle title in custom layout
    subtitle: ""
    imageUrl: "/IMAGE4.jpg"
    imageWidth: 150
    imageHeight: 150
    buttons: []  # We'll handle buttons in custom layout
  
  # Social media links (replaces deprecated .Site.Social)
  socialIcons:
    - name: "email"
      url: "mailto:nina.nikiforova@phd.unibocconi.it"
    - name: "twitter"
      url: "https://twitter.com/yourusername"  # Update with actual Twitter URL
    - name: "cv"
      url: "/cv.pdf"
  
  # Custom profile data for academic layout
  customProfile:
    name: "Nina Nikiforova"
    email: "nina.nikiforova@phd.unibocconi.it"
    cvLink: "/cv.pdf"
    imageUrl: "/IMAGE4.jpg"
    imageWidth: 150
    imageHeight: 150 
    shortDescription: "I am a fourth-year PhD student in Economics at Bocconi University."
    description: "My research interests lie in the fields of political economy and applied industrial organization."
    
    # Academic sections
    workingPapers:
      - title: "Discontent first, Ideology Later"
        coauthors: ""
        status: ""
        link: ""
        abstract: "Add your abstract here..."
      # Add more papers by duplicating the structure above
    
    # Publications section
   # publications:
      # - title: "Your Published Paper Title"
      #   coauthors: "Co-author Name"
      #   journal: "Journal Name, Vol. X, Year"
      #   link: "https://link-to-paper.com"
    
    # Work in progress section  
  #  worksInProgress:
      # - title: "Your Work in Progress Title"
      #   coauthors: "Co-author Name"
      #   status: "Draft available upon request"
  
  assets:
    favicon: "/apple-touch-icon.png"
    favicon16x16: "/apple-touch-icon.png"
    favicon32x32: "/apple-touch-icon.png"
    apple_touch_icon: "/apple-touch-icon.png"
    disableHLJS: true
    disableScrollBarStyle: true
  
  # Updated CSS reference
  assets:
    customCSS:
      - css/academic.css

markup:
  goldmark:
    renderer:
      unsafe: true

highlight:
  guessSyntax: true
  style: github
